- name: List files in /home/rosha
  hosts: all
  become: yes
  tasks:
    - name: Check if /home/rosha exists
      stat:
        path: /home/rosha
      register: dir_check

    - name: List all files in /home/rosha
      command: ls -l /home/rosha
      register: files_list
      when: dir_check.stat.exists  # Only run if the directory exists

    - name: Display the list of files
      debug:
        var: files_list.stdout_lines
