- name: List files in /home/rosha
  hosts: all
  become: yes
  tasks:
    - name: List all files in /home/rosha
      command: ls -l /home/rosha
      register: files_list

    - name: Display the list of files
      debug:
        var: files_list.stdout_lines
